import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../core/services/api.service';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './reports.component.html'
})
export class ReportsComponent implements OnInit {
  tab          = 0;
  scope        = 'LOANS';
  generatedBy  = '';
  generating   = false;
  genSuccess   = '';
  genError     = '';
  latestReport: any = null;

  reports:         any[] = [];
  filteredReports: any[] = [];
  scopeFilter      = '';
  loading          = false;
  selectedReport:  any = null;

  constructor(private api: ApiService, public auth: AuthService) {}

  ngOnInit(): void { this.generatedBy = this.auth.getDisplayName(); }

  generateReport(): void {
    this.generating  = true;
    this.genSuccess  = '';
    this.genError    = '';
    this.latestReport = null;

    this.api.generateReport(this.scope, this.generatedBy).subscribe({
      next: data => {
        this.generating   = false;
        this.latestReport = data;
        this.genSuccess   = `Report #${data.reportId} generated successfully for ${this.scope}`;
      },
      error: err => { this.generating = false; this.genError = err.error?.message || 'Generation failed'; }
    });
  }

  loadReports(): void {
    this.loading = true;
    this.api.getAllReports().subscribe({
      next:  d  => { this.reports = d; this.filteredReports = d; this.loading = false; },
      error: () => this.loading = false
    });
  }

  filterReports(): void {
    this.filteredReports = this.scopeFilter
        ? this.reports.filter(r => r.scope === this.scopeFilter)
        : this.reports;
  }

  selectReport(report: any): void {
    this.selectedReport = this.selectedReport?.reportId === report.reportId ? null : report;
  }

  deleteReport(id: number, event: Event): void {
    event.stopPropagation();
    if (!confirm('Delete this report permanently?')) return;
    this.api.deleteReport(id).subscribe({ next: () => this.loadReports(), error: () => {} });
  }

  formatMetrics(json: string): { key: string; value: string }[] {
    if (!json) return [];
    try {
      return Object.entries(JSON.parse(json)).map(([k, v]) => ({
        key:   k.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').replace(/^./, s => s.toUpperCase()),
        value: typeof v === 'object' ? JSON.stringify(v) : String(v)
      }));
    } catch { return [{ key: 'Data', value: json }]; }
  }

  downloadReportPdf(report: any): void {
    const rows = this.formatMetrics(report.metricsJSON).map(m => `
      <tr>
        <td style="padding:10px;border-bottom:1px solid #CFD8DC;font-weight:500;width:45%">${m.key}</td>
        <td style="padding:10px;border-bottom:1px solid #CFD8DC">${m.value}</td>
      </tr>`).join('');

    const win = window.open('', '_blank');
    if (!win) { alert('Please allow popups to download PDF'); return; }

    win.document.write(`<!DOCTYPE html><html><head>
      <title>FinSure Report #${report.reportId}</title>
      <style>
        body{font-family:Arial,sans-serif;padding:40px;color:#263238}
        .header{display:flex;justify-content:space-between;align-items:center;
                border-bottom:2px solid #1565C0;padding-bottom:16px;margin-bottom:24px}
        h1{color:#1565C0;margin:0;font-size:22px}
        .badge{background:#E3F2FD;color:#1565C0;padding:4px 12px;
               border-radius:12px;font-size:13px;font-weight:600}
        .meta{color:#546E7A;font-size:14px;margin-bottom:24px}
        table{width:100%;border-collapse:collapse}
        th{background:#1565C0;color:white;padding:12px;text-align:left;font-size:13px}
        .footer{margin-top:40px;text-align:center;color:#90A4AE;font-size:12px;
                border-top:1px solid #CFD8DC;padding-top:16px}
        @media print{button{display:none}}
      </style></head><body>
      <div class="header">
        <h1>FinSure — Report #${report.reportId}</h1>
        <span class="badge">${report.scope}</span>
      </div>
      <div class="meta">
        <p>Generated by: <strong>${report.generatedBy}</strong></p>
        <p>Generated at: <strong>${new Date(report.generatedAt).toLocaleString()}</strong></p>
      </div>
      <table>
        <thead><tr><th style="width:45%">Metric</th><th>Value</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <div class="footer">FinSure Cooperative Banking System — Confidential</div>
      </body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 500);
  }
}