spring.application.name=api-gateway
server.port=8079

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1
eureka.instance.non-secure-port=${server.port}
eureka.instance.instance-id=${spring.application.name}:${server.port}
app.jwt.secret=KZ9A$S3D@F8r#pL1!Zx7H*R6ewYV%TmUqC2M0

spring.cloud.gateway.server.webflux.routes[0].id=auth-register-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/register
spring.cloud.gateway.server.webflux.routes[0].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[1].id=identity-public-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/login,/auth/forgot-password

spring.cloud.gateway.server.webflux.routes[2].id=identity-protected-route
spring.cloud.gateway.server.webflux.routes[2].uri=lb://identity-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/users/**,/audit/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[3].id=member-service-route
spring.cloud.gateway.server.webflux.routes[3].uri=lb://MEMBER-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/members/**,/accounts/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[4].id=loan-service-route
spring.cloud.gateway.server.webflux.routes[4].uri=lb://LOAN-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/loans/**,/loan-approval/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[5].id=repayment-service-route
spring.cloud.gateway.server.webflux.routes[5].uri=lb://REPAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/repayments/**,/api/delinquencies/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[6].id=transaction-service-route
spring.cloud.gateway.server.webflux.routes[6].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/transactions/**,/api/account/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=JwtAuthFilter

spring.cloud.gateway.server.webflux.routes[7].id=reporting-service-route
spring.cloud.gateway.server.webflux.routes[7].uri=lb://REPORTING-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/reports/**,/kpi/**,/audit-packages/**,/api/notifications/**,/api/tasks/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=JwtAuthFilter