spring.application.name=config-server
server.port=8888

# GitHub repo URL
spring.cloud.config.server.git.uri=https://github.com/GowshikGS/finsure-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.refresh-rate=30000

# FIX - Skip SSL verification for CTS corporate network
# This tells JGit to not verify the SSL certificate
spring.cloud.config.server.git.skip-ssl-validation=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost